### ISSUE TITLE
Task feature

### ISSUE THREAD

**Issue by ivanDK5** [ivanDK5/equipo-4-to-do-api#3]
# Task

Implementar la estructura para la entidad de tarea en el desarrollo de api esto incluye

- [x] Añadir modelo de tarea.
- [x] Crear controlador para tarea y declarar funciones sin implementacion.
- [x] Crear rutas para la entidad de tarea.
- [x] Agregar rutas al archivo principal.
